In [1]:
import keras
keras.__version__


from keras.layers import Dense, Activation, Conv2D, Input
from keras.models import Sequential, load_model
from tensorflow.keras.optimizers import Adam

In [8]:
import matplotlib.image as mpimg

In [14]:
import numpy as np

In [2]:
def build_dqn(lr, n_actions, input_dims, fc1_dims, fc2_dims):
    model = Sequential([
        # Instead  of input_dims we will set the shape as [84,84]
        Input( shape=input_dims),

        # Let's temporarily set the shape to None
        # Input(fc1_dims),
        # Input( shape=None,input_shape=(input_dims  )),
        # The filter is the number of neurons in the first conv layer
        Conv2D(filters=128 , activation="relu", kernel_size=(5,5)),
        Conv2D(filters=256, activation="relu", kernel_size=(5,5)),
        Conv2D(filters=512, activation="relu", kernel_size=(5,5)),
        # If there will be errors persisting, relu activation will be added
        # Conv2D('relu', filter=128),

        # Later we might uncomment this part, however the paper hasn't mentioned anything regarding this type of syntax
        # Dense(fc2_dims),
        # Activation('relu'),
        Dense(n_actions) 
        # n_actions will be 3 (buy, sell, hold)
    ])
    model.compile(optimizer=Adam(lr=lr), loss='mse') #lr is the learning rate
    
    return model

In [6]:
q_eval = build_dqn(lr=0.005, n_actions=3, input_dims=[200,300,4],fc1_dims=84,fc2_dims=84)


c:\Users\Antoni\Anaconda3\lib\site-packages\keras\optimizer_v2\adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [10]:
img = mpimg.imread('images/TrainingDS/1,993.05,ASIANPAINT.png')

In [11]:
prediction = q_eval.predict(img)

ValueError: in user code:

    File "c:\Users\Antoni\Anaconda3\lib\site-packages\keras\engine\training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\Antoni\Anaconda3\lib\site-packages\keras\engine\training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\Antoni\Anaconda3\lib\site-packages\keras\engine\training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\Antoni\Anaconda3\lib\site-packages\keras\engine\training.py", line 1751, in predict_step
        return self(x, training=False)
    File "c:\Users\Antoni\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\Antoni\Anaconda3\lib\site-packages\keras\engine\input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 200, 300, 4), found shape=(None, 300, 4)


In [12]:
action_space = [i for i in range(3)]

In [13]:
print(action_space)

[0, 1, 2]


In [15]:
action_values = np.array(action_space, dtype=np.int8)

In [16]:
print(action_values)

[0 1 2]


In [21]:
action_indices = np.dot(0, action_values)
print(action_indices)


[0 0 0]


[0 1 2]
